# Pages CMS Configuration for RV Link Documentation Site
# https://pagescms.org

name: RV Link Docs
media:
  input: src/assets
  output: /src/assets

# Define reusable field sets using YAML anchors
x-standard-fields: &standard-fields
  - { name: title, label: Title, type: string, required: true }
  - { name: description, label: Description, type: text, required: true }
  - { name: body, label: Content, type: rich-text }

x-view-fields: &view-fields
  - { name: title, label: Title, type: string }
  - { name: description, label: Description, type: text }

collections:
  # Quick start pages in root docs folder
  - name: start-here
    label: 🚀 Start Here
    path: src/content/docs
    type: collection
    extension: mdx
    format: frontmatter
    filter:
      field: path
      operator: matches
      value: "^(gallery|purchase|index)\\.mdx$"
    view:
      fields: *view-fields
    fields: *standard-fields

  # Getting Started guides
  - name: getting-started
    label: 📖 Getting Started
    path: src/content/docs/getting-started
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Installation guides
  - name: installation
    label: 🛠️ Installation
    path: src/content/docs/installation
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Hardware documentation
  - name: hardware
    label: 🔌 Hardware
    path: src/content/docs/hardware
    type: collection
    extension: mdx
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Configuration guides
  - name: configuration
    label: ⚙️ Configuration
    path: src/content/docs/configuration
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Automation examples
  - name: automation
    label: 🤖 Automation
    path: src/content/docs/automation
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Monitoring features
  - name: monitoring
    label: 📊 Monitoring
    path: src/content/docs/monitoring
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Troubleshooting guides
  - name: troubleshooting
    label: 🔧 Troubleshooting
    path: src/content/docs/troubleshooting
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields

  # Core concepts
  - name: concepts
    label: 💡 Concepts
    path: src/content/docs/concepts
    type: collection
    extension: md
    format: frontmatter
    view:
      fields: *view-fields
    fields: *standard-fields