# Pages CMS Configuration for Libre Coach Documentation Site
media:
  input: src/assets
  output: src/assets

# ---------------------------------------
# Reusable Components
# ---------------------------------------
components:
  metadata:
    label: Page Metadata
    type: object
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }

  doc_template:
    type: object
    fields:
      - { name: metadata, label: Page Metadata, component: metadata }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Sidebar Label, type: string }
          - name: badge
            label: Badge
            type: object
            fields:
              - { name: text, label: Badge Text, type: string }
              - name: variant
                label: Badge Style
                type: select
                options:
                  values: [note, tip, caution, danger, success, default]
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: tableOfContents, label: Show TOC, type: boolean, default: true }
      - {
          name: lastUpdated,
          label: Show Last Updated,
          type: boolean,
          default: true,
        }
      - { name: body, label: Content, type: rich-text }

# ---------------------------------------
# Content Collections
# ---------------------------------------
content:
  - name: introduction
    label: "📖 Introduction"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, metadata.title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: page_data, component: doc_template }

  - name: installation
    label: "🛠️ Installation"
    type: collection
    path: src/content/docs/installation
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, metadata.title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: page_data, component: doc_template }

  - name: home-assistant
    label: "🏠 Home Assistant Setup"
    type: collection
    path: src/content/docs/home-assistant
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, metadata.title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: page_data, component: doc_template }

  - name: troubleshooting
    label: "🔧 Troubleshooting"
    type: collection
    path: src/content/docs/troubleshooting
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, metadata.title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: page_data, component: doc_template }

  - name: reference
    label: "📚 Reference"
    type: collection
    path: src/content/docs/reference
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, metadata.title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: page_data, component: doc_template }

  - name: community
    label: "👥 Community"
    type: collection
    path: src/content/docs/community
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, metadata.title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: page_data, component: doc_template }
