# Pages CMS Configuration for Libre Coach Documentation Site
media:
  input: src/assets
  output: src/assets

# ---------------------------------------
# Content Collections
# ---------------------------------------

content:
  - name: community
    label: "👥 Community"
    type: collection
    path: src/content/docs/community
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: home-assistant
    label: "🏠 Home Assistant Setup"
    type: collection
    path: src/content/docs/home-assistant
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: installation
    label: "🛠️ Installation"
    type: collection
    path: src/content/docs/installation
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: introduction
    label: "📖 Introduction"
    type: collection
    path: src/content/docs/introduction
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: reference
    label: "📚 Reference"
    type: collection
    path: src/content/docs/reference
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: start-here
    label: "🚀 Start Here"
    type: collection
    path: src/content/docs/start-here
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: troubleshooting
    label: "🔧 Troubleshooting"
    type: collection
    path: src/content/docs/troubleshooting
    filename: "{filename}.md"
    view:
      primary: filename
      fields: [filename, title, draft]
    fields:
      - { name: filename, label: Filename, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }
