# Pages CMS Configuration for RV Link Documentation Site
# https://pagescms.org

name: RV Link Docs

media:
  input: src/assets
  output: src/assets

components:
  metadata:
    label: Page Metadata
    type: object
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true

content:
  # ---------------------------------------
  # Introduction
  # ---------------------------------------
  - name: introduction
    label: "📖 Introduction"
    type: collection
    path: src/content/docs/introduction
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Installation
  # ---------------------------------------
  - name: installation
    label: "🛠️ Installation"
    type: collection
    path: src/content/docs/installation
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Home Assistant Setup
  # ---------------------------------------
  - name: home-assistant
    label: "🏠 Home Assistant Setup"
    type: collection
    path: src/content/docs/home-assistant
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Troubleshooting
  # ---------------------------------------
  - name: troubleshooting
    label: "🔧 Troubleshooting"
    type: collection
    path: src/content/docs/troubleshooting
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Reference
  # ---------------------------------------
  - name: reference
    label: "📚 Reference"
    type: collection
    path: src/content/docs/reference
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text

  # ---------------------------------------
  # Community
  # ---------------------------------------
  - name: community
    label: "👥 Community"
    type: collection
    path: src/content/docs/community
    format: yaml-frontmatter
    view:
      fields:
        - title
        - description
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: text
        required: true
      - name: body
        label: Content
        type: rich-text
