# Pages CMS Configuration for Libre Coach Documentation Site
media:
  input: src/assets
  output: src/assets

# ---------------------------------------
# Reusable Components
# ---------------------------------------
components:
  metadata:
    type: object
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }

# ---------------------------------------
# Content Collections
# ---------------------------------------

content:
  - name: introduction
    label: "📖 Introduction"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: installation
    label: "🛠️ Installation"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: home-assistant
    label: "🏠 Home Assistant Setup"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: troubleshooting
    label: "🔧 Troubleshooting"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: reference
    label: "📚 Reference"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }

  - name: community
    label: "👥 Community"
    type: collection
    path: src/content/docs/introduction
    filename: "{primary}.md"
    view:
      primary: slug
      fields: [slug, title, draft]
    fields:
      - { name: slug, label: URL Slug, type: string, required: true }
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string, required: true }
      - name: sidebar
        label: Sidebar Settings
        type: object
        fields:
          - { name: order, label: Order, type: number }
          - { name: label, label: Custom Label, type: string }
      - { name: draft, label: Draft, type: boolean, default: false }
      - { name: body, label: Content, type: rich-text }
